### ISSUE TITLE
Port content-hub and sharing code from uMastonauts?

### ISSUE THREAD

**Issue by poVoq** [poVoq/hubzilla-web#5]
It seems like in the somewhat diverged upstream uMastonauts there is an implementation of sharing through the content hub.

Would be nice to backport that here, but probably more difficult that it looks at first glance. Help appreciated.

**Comment by poVoq** [comment]
Hubzilla allows text and link sharing via URL:

Text: "/rpost?body="
Links: "/rpost?f=&url="

**Comment by poVoq** [comment]
I started implementing this, but while it opens uHubzilla on share, it does not change to the /rpost link.
No idea why, as the code looks the same as in uMastonauts :(

**Comment by poVoq** [comment]
@ChristianPauly Since you probably have a better idea of this code, any help?

**Comment by krille-chan** [comment]
Hey I have taken a look into your code and it looks fine so far. You have the hook in the manifest, the content hub config file, the Connection in the qml code and you are manipulating the url then. No idea why this doesnt work.

**Comment by poVoq** [comment]
hmm, thanks a lot for looking into that. So I guess it must be some small issue somewhere that is easy to overlook. Argg, debugging that will be difficult :(

**Comment by poVoq** [comment]
Error log gives me this:
`file:///opt/click.ubuntu.com/hubzilla-web.povoq/0.0.6/qml/pages/HubzillaWebview.qml:33:2: QML Connections: Cannot assign to non-existent property "onShareRequested"`
and
`file:///opt/click.ubuntu.com/hubzilla-web.povoq/0.0.6/qml/pages/HubzillaWebview.qml:33: ReferenceError: ContentHub is not defined`
But no idea what that means...

**Comment by poVoq** [comment]
Got help on the ubports matrix channel, it was missing the `import Ubuntu.Content 1.3` part.
